PoGoFriends/Models/ErrorViewModel.cs
using System;

namespace PoGoFriends.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PoGoFriends/Models/Friends.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PoGoFriends.Models
{
    public class Friends
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(30, MinimumLength = 4)]
        public string Nickname { get; set; }
        [Required]
        public string Country { get; set; }
        [DisplayName("Trainer Code")]
        [Required]
        [RegularExpression("(^[0-9]{12}$)", ErrorMessage = "Trainer Code must be 12 digits and contain only numbers.")]
        public long Code { get; set; }

        [DisplayName("Leave a note")]
        [StringLength(200, ErrorMessage = "The maximum length of the message is 200 characters")]
        public string TextBox { get; set; }
    }
}

PoGoFriends/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using PoGoFriends.Data;
using PoGoFriends.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PoGoFriends.Controllers
{
    public class FriendController : Controller
    {

        private readonly ApplicationDbContext _db;

        public FriendController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Friends> objList = _db.Friends;
            return View(objList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Friends friend)
        {
           if(ModelState.IsValid)
            {
                _db.Add(friend);
                _db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(friend);
        }

    }
}

PoGoFriends/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PoGoFriends.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PoGoFriends.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PoGoFriends/Views/Friend/Create.cshtml
@model PoGoFriends.Models.Friends
@{
    ViewData["Title"] = "Create Request";
}


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-8">
            <h2 class="text-primary">Leave your friend request</h2>
        </div>
        <div class="col-4 text-right">
            <a asp-controller="Friend" asp-action="Index" class="btn btn-primary">Go Back</a>
        </div>
    </div>
    <br />
    <form asp-action="Create" method="post" data-ajax="true" data-ajax-success="emptyForm()" id="createForm">
        <div class="border p-3">
            <div class="form-group">
                <label asp-for="Nickname"></label>
                <input asp-for="Nickname" class="form-control" id="nickname" />
                <span asp-validation-for="Nickname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code"></label>
                <input asp-for="Code" class="form-control" id="code" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country"></label>
                <input asp-for="Country" class="form-control" id="country" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TextBox"></label>
                <textarea asp-for="TextBox" class="form-control" id="textbox"></textarea>
            </div>
            <button type="submit" class="btn btn-danger w-25">Create</button>
        </div>
    </form>

    <div class="col-6 pt-3">
        <p class="text-success" style="display:none" id="datasent">Friend request sent! </p>
    </div>

</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script>
            function emptyForm() {

                // Clear form
                document.getElementById("createForm").reset();

                // Send success message
                $("#datasent").show();
                setTimeout(function () {
                    $("#datasent").hide();
                }, 5000);

            }
            
        </script>
    }
}

PoGoFriends/Views/Friend/Index.cshtml
@model IEnumerable<PoGoFriends.Models.Friends>
@{
    ViewData["Title"] = "Find a new friend!";

}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-8">
            <h2 class="text-primary">Make new friends</h2>
        </div>
        <div class="col-4 text-right">
            <a asp-controller="Friend" asp-action="Create" class="btn btn-primary">Create Request</a>
        </div>
    </div>
    <br />

        <div class="card-columns">
            @if (Model.Count() > 0)
            {

                @foreach (var obj in Model.Reverse())
                {
                    <div class="card m-4 border-success">
                        <div class="card-header bg-light border-secondary">@Html.DisplayNameFor(model => model.Code): @obj.Code</div>
                        <div class="card-body border-secondary">
                            <h5 class="card-title">@obj.Nickname</h5>
                            <p class="card-text">@obj.TextBox</p>
                        </div>
                        <div class="card-footer bg-transparent">@Html.DisplayNameFor(model => model.Country): @obj.Country</div>
                    </div>
                    <br />
                }
            }
            else
            {
                <div class="container">
                    <p>No friends yet</p>
                </div>
            }
        </div>
    </div>

PoGoFriends/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}


<div class="container p-3">
    <div class="row pt-4">
            <h2>What is Pokemon Go?</h2>
        </div>

    <div class="container-fluid p-3">
        <div class="row">
            <div class="col-sm-6">
                <img src="~/images/pokemon-go2.jpg" class="img-responsive" style="width:100%" alt="A person is holding a phone in their hand, which shows Pokemon Go game sign up screen">
            </div>
            <div class="col-sm-6">
                <p>
                    Pokémon Go is a 2016 augmented reality (AR) mobile game developed and published by Niantic in collaboration with Nintendo and The Pokémon Company for iOS and Android devices. A part of the Pokémon franchise, the game is the result of a collaboration between Niantic, Nintendo and The Pokémon Company. It uses mobile devices with GPS to locate, capture, train, and
                    battle virtual creatures, called Pokémon, which appear as if they are in the player's real-world location. The game is free-to-play; it uses a freemium business model combined with local advertising and supports in-app purchases for additional in-game items. The game launched with around 150 species of Pokémon, which had increased to around 600 by 2020.
                </p>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-sm-6">
                <img src="~/images/pokemon-go3.jpg" class="img-responsive" style="width:100%" alt="Two kids playing pokemon go outdoors on their phones">
            </div>
            <div class="col-sm-6">
                <p>
                    Pokémon Go was released to mixed reviews; critics praised the concept but criticized technical problems. It was one of the most used and profitable mobile apps in 2016, having been downloaded more than 500 million times worldwide by the end of the year. It is credited with popularizing location-based and AR technology, promoting physical activity, and helping local businesses grow due to increased foot traffic. However, it attracted controversy for contributing to accidents and creating public nuisances. Various governments expressed concerns about security, and some countries regulate its use. The game had over 147 million monthly active users by May 2018, over a billion global downloads by early 2019,
                    and grossed more than $6 billion in revenue as of 2020.
                </p>
            </div>
        </div>
        <br />
            <p> Source: <a href="https://en.wikipedia.org/wiki/Pok%C3%A9mon_Go">Wikipedia</a> </p>
        </div>
    </div>

PoGoFriends/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<div class="container p-3">
    <div class="row pt-4">
        <h2>Any Questions?</h2>
    </div>
</div>
<div class="container-fluid pt-5 text-center">
    <div class="row">
        <div class="col-lg-4 col-sm-6 mb-4">
            <div class="card border-0 shadow rounded-xs pt-5">
                <div class="card-body">
                    <img src="/images/pokemon.png"  class="img-responsive" style="width:40%" alt="A drawn brown pokemon" />
                    <h4 class="mt-4 mb-3">Technical Support</h4>
                    <p>Tech@pogo.com</p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-4">
            <div class="card border-0 shadow rounded-xs pt-5">
                <div class="card-body">
                    <img src="/images/pokeball.png" class="img-responsive" style="width:40%" alt="A drawn red and white pokemon ball">
                    <h4 class="mt-4 mb-3">Pokemon Support</h4>
                    <p>Pokemon@pogo.com</p>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-sm-6 mb-4">
            <div class="card border-0 shadow rounded-xs pt-5">
                <div class="card-body">
                    <img src="/images/pikachu.png" class="img-responsive" style="width:40%" alt="A drawn Pikachu pokemon smiling">
                    <h4 class="mt-4 mb-3">Friend Support</h4>
                    <p>Friends@pogo.com</p>
                </div>
            </div>
        </div>
    </div>
    </div>

PoGoFriends/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container-fluid bg-1 text-light">
    <div class="bgimage">
        <div class="container">
            <h1 class="display-4">PoGo Friends Maker</h1>
            <p class="lead">Welcome to make new PoGo Friends!</p>
        </div>
    </div>
</div>

<div class="container-fluid bg-2 pt-5 text-center">
    <h3>Want to find new Pokemon Go friends?</h3>
    <p>You have come to the right place. On this site, you can browse friend requests or leave yours. Where do you want to start?</p>
    <a asp-controller="Friend" asp-action="Create" class="btn btn-success m-2">Create Request</a> <a asp-controller="Friend" asp-action="Index" class="btn btn-success m-2">Browse Request</a>
</div>

<div class="container-fluid bg-3 text-center pt-5">
    <div class="row">
        <div class="col-sm-4">
            <img src="~/images/pokemon1.jpg" class="img-responsive margin" style="width:100%" alt="A person is holding a phone in their hand, which shows a Pokemon Go game">
        </div>
        <div class="col-sm-4">
            <img src="/images/pokemon2.jpg" class="img-responsive margin" style="width:100%" alt="A person is outdoors playing a Pokemon Go game">
        </div>
        <div class="col-sm-4">
            <img src="/images/pokemon3.jpg" class="img-responsive margin" style="width:100%" alt="A person browses pokemons on their phone">
        </div>
    </div>
</div>

PoGoFriends/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PoGoFriends</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PoGoFriends</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="About">About Pokemon Go</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Friend" asp-action="Index">Find Friends</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Friend" asp-action="Create">Create Friend Request</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="container-fluid">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PoGoFriends
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>